[project]
name = "patient-data-backend"
description = "Pateient data access backend infrastructure"
version = "0.1"
readme = "README"
requires-python = ">=3.9"

[tool.poetry.dependencies]
pydantic = "^2.12.5"
boto3 = "^1.42.40"
botocore = "^1.42.40"
